### PR TITLE
Add fix for pcsc 2.3.0 to flathub-beta

### PR DESCRIPTION
**Pull request by suntorytimed**
Submitting changes from https://github.com/flathub/com.yubico.yubioath/pull/91 to beta branch to release a fix for https://github.com/flathub/com.yubico.yubioath/issues/90 to flathub-beta

### CODE REVIEW

**Comment by suntorytimed** [comment]
I don't know why, but unfortunately only someone with write access to the repo can resolve the merge conflicts. Rebasing the beta branch prior to the request and sending that in resulted in the same conflicts.

**Comment by Lunarequest** [comment]
the beta branch has diverged to far to get a pr including all the changes from main. I would suggest just cherry picking individual commits

**Comment by suntorytimed** [comment]
As said, force pushing https://github.com/hafeoz/com.yubico.yubioath/tree/master to beta would probably be best. The changes in beta are irrelevant for master anyways as far as I can tell. And the beta branch is still at version 6.0.0.

**Comment by Lunarequest** [comment]
force pushing is explicitly disabled by the flathub admins for beta and master branches

**Pull request closed without merging**
