### PR TITLE
Yubioath Desktop 5.0.5

### PR DESCRIPTION
**Pull request by ai**

### CODE REVIEW

**Comment by ai** [comment]
@bilelmoussaoui sorry for bothering you again, but how to use `poetry-core` in FLatpak builder?

I added `poetry-core` dependency to `com.yubico.yubioath.json`: https://github.com/flathub/com.yubico.yubioath/blob/06d1a2e63374121d284b81a1f75ca5fcc0d93560/com.yubico.yubioath.json#L213-L225

But `pip3 install` of `yubikey-manager` still doesn’t see the dependency:

```
========================================================================
Building module yubikey-manager in /srv/buildbot/worker/build-x86_64-6/build/.flatpak-builder/build/yubikey-manager-1
========================================================================
]2;flatpak-builder: Building yubikey-managerFB: Running: tar xf /srv/buildbot/worker/build-x86_64-6/build/.flatpak-builder/downloads/998f804a66695feeb3a48ba200320850243aa605d6d4edcb30bea4cc349aea21/yubikey-manager-4.0.2.tar.gz --no-same-owner --strip-components=1 -z
]2;flatpak-builder: Installing yubikey-managerRunning: pip3 install --prefix /app --no-deps .
FB: Running: flatpak build --die-with-parent --env=FLATPAK_BUILDER_BUILDDIR=/run/build/yubikey-manager --nofilesystem=host --filesystem=/srv/buildbot/worker/build-x86_64-6/build/.flatpak-builder/build/yubikey-manager-1 --bind-mount=/run/build/yubikey-manager=/srv/buildbot/worker/build-x86_64-6/build/.flatpak-builder/build/yubikey-manager-1 --build-dir=/run/build/yubikey-manager --bind-mount=/run/ccache=/srv/buildbot/worker/build-x86_64-6/build/.flatpak-builder/ccache --unshare=network --env=SOURCE_DATE_EPOCH=1619178559 '--env=CFLAGS=-O2 -g -pipe -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection ' '--env=CXXFLAGS=-O2 -g -pipe -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection ' '--env=LDFLAGS=-L/app/lib -Wl,-z,relro,-z,now -Wl,--as-needed ' --env=CCACHE_DIR=/run/ccache/disabled --env=PATH=/app/bin:/usr/bin --env=LD_LIBRARY_PATH=/app/lib --env=PKG_CONFIG_PATH=/app/lib/pkgconfig:/app/share/pkgconfig:/usr/lib/pkgconfig:/usr/share/pkgconfig --env=FLATPAK_BUILDER_N_JOBS=48 /srv/buildbot/worker/build-x86_64-6/build/.flatpak-builder/rofiles/rofiles-Mhx1DQ /bin/sh -c 'pip3 install --prefix /app --no-deps .'
Processing /run/build/yubikey-manager
  Installing build dependencies ... [?25l-
 
\
 
|
 
/
 
-
 
error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 /usr/lib/python3.8/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-mgeu4w4p/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'poetry-core>=1.0.0'
       cwd: None
  Complete output (7 lines):
  WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f354feb9760>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/poetry-core/
  WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f354feb9970>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/poetry-core/
  WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f354feb9b20>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/poetry-core/
  WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f354feb9cd0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/poetry-core/
  WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f354feb9e80>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/poetry-core/
  ERROR: Could not find a version that satisfies the requirement poetry-core>=1.0.0
  ERROR: No matching distribution found for poetry-core>=1.0.0
```

**Comment by Erick555** [comment]
You may sitck with 3.1.2 ver of yubikey-manager for the time being in ordrer to not block entire upgrade on this and look at fix later.

**Comment by ai** [comment]
@Erick555 the main feature of 5.0.5 is using Yubikey Manager 4. Any idea how to fix the build problem?

**Comment by Erick555** [comment]
It add compatibility with it but doesn't require it. BTW: ver 4 drops dependencies on libusb/pyusb.

**Comment by ai** [comment]
> It add compatibility with it but doesn't require it

But there is no other changes https://github.com/Yubico/yubioath-desktop/releases/tag/yubioath-desktop-5.0.5

> BTW: ver 4 drops dependencies on libusb/pyusb.

Great, I will remove installing them from he script.

**Pull request merged**
