### PR TITLE
Fix tray support

### PR DESCRIPTION
**Pull request by iavael**
Allow talk to org.kde.StatusNotifierWatcher dbus endpoint

### CODE REVIEW

**Comment by ai** [comment]
LGTM. But afraid we will need to wait new release of yubioath to release it.

**Comment by Erick555** [comment]
@ai every commit you push to master branch will be automatically released to flathub.

**Comment by ai** [comment]
@Erick555 but we didn't changed the version

**Comment by Erick555** [comment]
As I said every new commit results in rebuild whole app and publishes it to flathub. It doesn't matter if you changed the version or not. Flatpak updates apps every time hash commit changes, version is just optional information for users otherwise it's not used for anything.

**Pull request merged**
